### ISSUE TITLE
[1.2.3] Non-Functional Requirements

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#10]
<details><summary>Task Title ID</summary>
<p>
#10
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Details</summary>
<p>

` Create a non-functional requirements that are used to judge the operation of a system rather than specific behaviors. Will focus on attributes like performance, usability, reliability, security and other aspects that are not related to specific functionalities`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Goals</summary>
<p>

`Able to come up with the completed non-functional user requirements for the client`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Success - Completion Details:</summary>
<p>

`Clear and precise non-functional user requirements in details to be updated in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`2 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`11/09/2023` - `12/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [x] Hakim

- [ ] Zac

- [ ] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by Codestian** [comment]
<details><summary>Work Done</summary>
<p>

- The system should be designed to scale efficiently to accommodate an increasing number of users and data. (Scalability)
- The system should be designed to be consistent for different platforms. (Consistency)
- The system should be dependable and operate consistently without unexpected failures. (Stability)
- The system should provide meaningful error messages and handle errors gracefully without exposing sensitive information.
- A comprehensive and up-to-date documentation will be provided to all users to provide assistance.


</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`11/09/2023` - `12/09/2023`

</p>
</details>
