### ISSUE TITLE
[1.3.2] Use Case Descriptions

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#11]
<details><summary>Task Title ID</summary>
<p>
#11
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

` Create all the use cases description to provide a structured and detailed view of how the system will behave from the perspective of the end-users, ensuring the final product meets their needs and expections. `

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Able to come up with the completed use case descriptions for the client`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Detailed use case descriptions that is clear and concise to be updated in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`4 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `17/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [x] Hakim

- [ ] Zac

- [ ] Brendan

- [x] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by rudhifnd** [comment]
<details><summary>Work Done</summary>
<p>



![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/5a2ac51d-d5cc-4ad3-a718-ac54f8fe2f59)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/caf21ba4-a543-4530-aa42-0bf843bd3687)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/e711f655-0566-4122-82d3-e0982e83fd17)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/a875aa25-2bf1-48ca-a255-ff8035c795b6)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/889c3cd7-243a-4f18-8ee1-3c79786e5bd5)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/37a93f6e-bcf9-4dbd-b244-d0c13cb18801)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/4725fdec-de6b-435f-985c-381aeb86c513)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/a64e6373-d7a6-4087-a9bb-5475ee7bd138)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/b3218534-32a9-4bba-ac39-3116dee2a351)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/d4257974-5bfa-407b-ac0f-37ec2f0eae5a)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/9db0e320-5c64-4d39-ac28-e81a9f08bb0c)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/111c32a8-0cf1-4710-a122-69dfa5758fba)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/ee6e163c-ffe7-47c6-a1d8-7eba937ea131)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/e5fadc80-1a25-4aba-a752-44c2188a95f6)



</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`11/09/2023` - `12/09/2023`

</p>
</details>
