### ISSUE TITLE
[1.2.1] User Interface Requirements

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#14]
<details><summary>Task Title ID</summary>
<p>
#14
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

` Create user interface requirements that are necessary for creating an effective and user-friendly interface for the system .`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Able to come up with the completed user interface requirements for the client`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Clear and precise user interface requirements in details to be updated in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`3 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `16/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [x] Zac

- [ ] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`Medium priority`

</p>
</details>

**Comment by Cazyrah** [comment]
<details><summary>Work Done</summary>
<p>

USER INTERFACE REQUIREMENTS

Login Page:
- The main entry point for users to access the system.
- Users interacts with the system by entering their Username and Password into the input fields.
- The system interface includes a Submit button to initiate the login process.
- Error message will be displayed in case of Empty fields or incorrect login credentials.

Landing Page:
- After successful login, users are redirected to the Landing Page.
- The Landing Page serves as the central hub for accessing the system functionalities.
- Staff can see their job assignments, notifications, and links to other sections of the application.
- manager can see the overview of the workload allocation, top three staff with the lowest workload, and all highlighted staff over 40 hours of jobs allocated.

Account Management Page:
- IT Administrator have access to pages for creating new user accounts and modifying existing ones.
- The interfaces include forms for entering new user information, privileges, and account details.
- Error messages will be displayed for missing or invalid information.
- Modifications to existing accounts involve selecting a specific account from the list of existing accounts and editing its details.

Job Preference Page:
- Staff members access this page to set their job preferences for upcoming weeks.
- The interface includes a calendar showing upcoming weeks, and users can select a week to set preferences.
- Users can specify their preferred day, time, location, and type of service using input fields or dropdown menus.
- A Submit button allows users to save their preferences.

Leave Request Page:
- Staff members access this page to submit annual leave requests.
- Staff members interact by selecting a date for leave, providing a reason, and submitting the request.
- A Submit button allows staff members to submit their leave request.
- Error message will be displayed in case of invalid dates, no provided reason, or insufficient annual leave.

Leave Request Management Page:
- Managers access this page to review and manage leave requests from staff members.
- The interface displays a list of pending leave requests, and managers can choose to accept, deny, or leave it pending.
- Notifications are sent to staff members upon updated status of their requests.

Vehicle Status Management Page::
- Both managers and drivers can access this page to manage vehicle status and information.
- The interface shows a list of available vehicles along with their details including status (Servicing or Operable), Vehicle Number, and Vehicle Model
- Both managers and drivers can select a vehicle to modify its information or status.
- Managers can delete or add new vehicles.

Workload Management Page:
- Managers access this page to view available jobs, assign jobs to staff, and create workload drafts.
- The interface displays a list of available jobs, and managers can select specific jobs and assign them to staff members.
- A calendar view shows upcoming days for scheduling.
- Managers can view staff preferences and make assignments accordingly.

Workload Draft Management Page:
- Managers access this page to review workload drafts, check job assignment statuses, and finalize workloads.
- The interface displays existing drafts, and managers can select a draft for review.
- Managers may finalize drafts, delete them, or make no change.
- Managers can assign backup staff to workload drafts.
- A calendar view show the draft details, and managers can assign backup staff accordingly.

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `16/09/2023`

</p>
</details>

**Comment by Cazyrah** [comment]
<details><summary>Work Done</summary>
<p>

-UPDATE-

USER INTERFACE REQUIREMENTS

Company logo
Logo should contain both the logo and the company name in a horizontal manner.
Size of the logo should be 500 x 1000 pixels, and no bigger than 2MB.

Theme/Color Scheme
The color system of the interface should include the following in hex format:
- Primary - #12486B
- Secondary - #419197
- Background - #FFFFFF

Typography
- Header
1. Style - Squada One (display)
2. Size - 40px
3. Weight - Bold
4. Letter Spacing - 3px
5. Color - #008000

- Body
1. Style - Open sans (sans-serif)
2. Size - 16px
3. Weight - Normal
4. Letter Spacing - 2px
5. Color - #2E8B57

- Footer
1. Style - Tahoma (sans-serif)
2. Size - 8px
3. Weight - Normal
4. Letter Spacing - 1px
5. Color - #8D918D

Iconography
- Icon set - Font Awesome
1. Style - Solid
2. Size - 25px
3. Color - #EBF4FA

Form Elements
- Input Fields
1. Style - Rounded Border
2. Border Width - 2px solid
3. Background Color - #EBF4FA

- Dropdowns
1. Style - Standard Dropdown Arrow
2. Background Color - #D5D6EA

- Buttons
1. Style - Rounded Corner
2. Color - #6960E3
3. Hover - Slight shadow on hover

The language and locale shall be set to English and Singapore (en-sg).

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`19/09/2023` - `22/09/2023`

</p>
</details>
