### ISSUE TITLE
[1.2.3.2] Safety and Security Requirements

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#16]
<details><summary>Task Title ID</summary>
<p>
#16
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Details</summary>
<p>

` Create Safety and security requirements that are concerned with possible loss, damage, or harm that could
result from the use of the product. Define any safeguards or actions that must be taken, as well as
actions that must be prevented .`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Goals</summary>
<p>

`Able to come up with the completed safety and security requirements for the client`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Success - Completion Details:</summary>
<p>

`Clear and precise safety and security requirements in details to be updated in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`3 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `16/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [ ] Brendan

- [x] Rudhi

- [ ] Malcolm 
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`Medium priority`

</p>
</details>

**Comment by rudhifnd** [comment]
<details><summary>Work Done</summary>
<p>

Security and Safety Requirements

1. Sensitive data including employee information, login details and schedules should be encrypted in all states including during transmission using AES-256.
2. User roles and permissions must be clearly defined.
3. Users only have access to data and features that are assigned to their roles.
4. System data including scheduling and employee information should be automatically backed up every week and stored securely offsite.
5. User passwords must align with the password policy assigned to be considered valid.
6. Passwords should contain at least 10 characters including 1 uppercase, and 1 symbol.
7. The system should keep track of all user activities including logins, user actions and data access, with timestamps and user identifiers.
8. Any access to the system through the web should use HTTPS with valid SSL/TLS certificates to encrypt data transmission
9. The system should mask any password fields to prevent potential shoulder surfing.

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`13/09/2023` - `14/09/2023`

</p>
</details>
