### ISSUE TITLE
[1.5.3] Glossary(Data Dictionary)

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#17]
<details><summary>Task Title ID</summary>
<p>
#17
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Details</summary>
<p>

` Create Data Dictionary to track all the different variables, states and functional requirements that is described. Layout the definition of terms used and align the readers to the authors perspectives .`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Goals</summary>
<p>

`Able to come up with the completed data dictionary which include list of all ocnstants, state variables, inputs and outputs in a table. In the table, include the description of these items as well as all related operations and requirements`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Success - Completion Details:</summary>
<p>

`Clear and precise data dictionary in details to be updated in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`3 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `16/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [x] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`Medium priority`

</p>
</details>

**Comment by bren37** [comment]
<details><summary>Work Done</summary>
<p>

### **Glossary** 

- IT administrator
A person who is responsible for managing the addition of new staff and managers into the system.
- Manager
A person who views staff workload and allocates aircon jobs to the staff.
- Staff
A person who carries out the tasks by the company consists of technicians and drivers.
- Technician
A person who does the installation or servicing of the aircon.
- Driver
A person who operates the company's vans used for transportation to job sites.
- Landing page
The initial page of the web application that provides information to the manager and staff.
- Job preference 
The type of jobs that staff prefer.
- Job allocation
The process of assigning jobs to staff.
- Staff Availability
Information relating to when the staff is free to work.
- Weekly job assignments
Jobs that are distributed to staff for the week.
- Overall workload
The total amount of work that staff has within a period of time.
- Deadline
The specified time that staff must submit their availability for the upcoming week.
- Reject
The Staff decline the job allocation given to them.
- Case-by-case basis
Handling job changes requests made by staff who miss the weekly deadline, based on circumstances.









</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `16/09/2023`

</p>
</details>
