### ISSUE TITLE
[1.2.4] Product Functionality

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#22]
<details><summary>Task Title ID</summary>
<p>
#22
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Details</summary>
<p>

` Create product functionality to  show the major functions the product must perform or must let the user perform.`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Goals</summary>
<p>

`Provide a high-level summary to show the features and capabilities that a product offers to its users`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Success - Completion Details:</summary>
<p>

`Clear and precise product functionality in details to be updated in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`3 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `16/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [x] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`Medium priority`

</p>
</details>

**Comment by bren37** [comment]
<details><summary>Work Done</summary>
<p>

The following is the list of all the overall functions of the product:

- The product shall be accessible through a web browser.
- The product shall allow the IT administrator to manage the accounts.
- The product shall allow user to login with their account.
- The product shall allow manager to view top 3 staff availability during job allocation.
- The product shall allow manager to allocate jobs to the staff.
- The product shall allow manager to view the workload of all staff on the landing page.
- The product shall allow staff to add and edit their availabilities up to 5 weeks ahead of time.
- The product shall allow staff to indicate their job preference for the week.
- The product shall allow staff to view their weekly job assignments on the landing page
- The product shall allow staff to view their overall workload for the month on the landing page.
- The product shall allow staff to reject jobs assigned to them.
- The product shall allow staff to apply for annual leave.










</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `16/09/2023`

</p>
</details>

**Comment by bren37** [comment]
<details><summary>Work Done</summary>
<p>

The following is the updated list of the Product Functionality:

**PF1:** The product shall allow the IT administrator to manage the accounts.
**PF2:** The product shall allow users to login with their account.
**PF3:** The product shall allow the manager to add jobs.
**PF4:** The product shall allow the manager to allocate jobs to the staff.
**PF5:** The product shall allow the manager to view top 3 staff availability during job allocation.
**PF6:** The product shall allow the manager to view the workload of all staff on the landing page.
**PF7:** The product shall allow the manager to view weekly and monthly jobs.
**PF8:** The product shall allow the manager to finalize the weekly schedule.
**PF9:** The product shall allow staff to add and edit their availability up to 5 weeks ahead of time.
**PF10:** The product shall allow staff to indicate their job preference for the week.
**PF11:** The product shall allow staff to view their finalized weekly job assignments on the landing page.
**PF12:** The product shall allow staff to view their overall workload for the month on the landing page.
**PF13:** The product shall allow staff to reject jobs assigned to them.
**PF14:** The product shall allow staff to submit their leave request.
**PF15:** The product shall allow staff and manager to filter jobs on the landing page.
**PF16:** The product shall allow staff and manager to view vehicle status.
**PF17:** The product shall allow the manager to edit the vehicle status.













</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`Updated the list of Product Functionality after further discussion`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`22/09/2023` - `22/09/2023`

</p>
</details>
