### ISSUE TITLE
[1.5.1] Product Scope, Background Lit and Intended audience

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#24]
<details><summary>Task Title ID</summary>
<p>
#24
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Details</summary>
<p>

` Define the product scope, related background literature and intended audience.`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Goals</summary>
<p>

`Relevant background lit and well defined product scope is established`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Success - Completion Details:</summary>
<p>

`The detailed task to be posted and updated to the report and update in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`1 day`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`18/09/2023` - `18/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [x] Brendan

- [x] Rudhi

- [ ] Malcolm 
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`Low priority`

</p>
</details>

**Comment by DeNhAiKal** [comment]
<details><summary>Work Done</summary>
<p>

### Background Lit

The related background literature encompasses a diverse range of studies vital to the development of an effective workload management system within the context of an aircon service team. McFarland’s practical guide called ‘The missing manual’ on JavaScript and jQuery is instrumental in steering the technical development of the web-based application providing a robust foundation for the project’s implementation. Currently the competing softwares are Microsoft Project which is designed, Asana, Smartsheet to help managers set goals for the team and create schedules for the staff and handle the workload. The most prominent software of them all is the Microsoft Project, has been around for about 30 years and extremely compatible with Office 365 which plenty of companies are using. There is also the traditional manual technique, which assigns duties to the employees using an Excel spreadsheet, but this is not the most optimal way to do it. Spreadsheets are not user-friendly, it is hard to visualize data as a whole, are not secure where dishonest staff can share customer data, most damaging is that spreadsheets are prone to errors. Due to their high costs and ineffectiveness for managers, all of the currently available software is not the greatest option for the business. For example, utilizing Microsoft Projects will be costly in the long term and having limited customization will not be effective for the managers. On the other hand,spreadsheets are error prone. Thus, creating a custom workload management website will help to be tailored to specific needs, have complete control and it is more scalable in the long run. These diverse sources collectively form a well-rounded knowledge base that will underpin the creation of innovative and effective workload management systems.

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`18/09/2023` - `18/09/2023`

</p>
</details>

**Comment by bren37** [comment]
<details><summary>Work Done</summary>
<p>

### Project Scope

The scope of the product is a web application for the aircon retailer company to streamline and optimize their work allocation process for the manager and staff. The purpose is to provide the manager an overview visualisation of the staff workloads, allowing them to allocate jobs to the staff per week. It prioritizes workload efficiency by highlighting low workload and high workload staff.

The product allows staff to plan their availability up to 5 weeks in advance and their job preferences which helps the manager to plan based on their job preferences and availability effortlessly. Overall, the product’s scope is to improve job allocation within the aircon retailer company. 




</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`18/09/2023` - `18/09/2023`

</p>
</details>

**Comment by rudhifnd** [comment]
<details><summary>Work Done</summary>
<p>

### Intended Audience

This document is catered to different groups of readers, each with specific interest and needs. The audience primarily includes developers who will be involved in designing and implementing the system, project managers who oversee the system’s development, and end-users who will regularly interact with the system. In addition, testers who want to validate the system with its requirements may find this document useful.

The remaining portion of this document is organised into multiple sections. It begins by giving an overall description of the system, which includes an in-depth explanation about the product’s fundamental aspects and its functionality. Next, the document explains the specific requirements for the system where it thoroughly states the user interface requirements, the functional requirements and the non-functional requirements. Accompanied by these requirements is a use case model which gives a modelled representation of how the system will function. Following that the document offers valuable information for project managers and stakeholders who are responsible for the estimation and planning of the project. This section includes a very detailed timeline to make sure the project progresses well. 

For the optimal reading experience, readers are advised to begin with the introduction which provides context for the following sections. Developers and testers can read the Specific Requirements section for any technicalities of the system. Readers may refer to the use case descriptions in Appendix A to aid them in further understanding of each use case in the use case model.

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`18/09/2023` - `18/09/2023`

</p>
</details>
