### ISSUE TITLE
[1.5.2] Product Overview

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#25]
<details><summary>Task Title ID</summary>
<p>
#25
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Details</summary>
<p>

` Define the product overview to be clear and precise .`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Goals</summary>
<p>

`A well defined product overview is established`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Success - Completion Details:</summary>
<p>

`The detailed task to be posted and updated to the report and update in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`1 day`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`18/09/2023` - `18/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [x] Hakim

- [ ] Zac

- [ ] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`Low priority`

</p>
</details>

**Comment by malcolmkzh** [comment]
<details><summary>Work Done</summary>
<p>

The Workload Management System (WMS) is a self-contained software product designed to improve the way employee workloads are managed within the company. It is a stand-alone solution, made to replace the previous manual methods of workload management done through Excel spreadsheets, offering a more interactive and visually intuitive approach. The workload management system consists of 2 main components: an Employee Portal for employees to view their assigned jobs and provide their availability, and an Manager Dashboard, which enables the manager to visualize the jobs status and allocate jobs efficiently. 

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/25952539/c899f723-4a32-4c2a-8dcd-6a65aeec0526)

Staff, Manager and IT Administrator interact with the workload management system which is a website hosted on a web server. The web server is connected to the database which stores information about the workload management system.
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`18/09/2023` - `18/09/2023`

</p>
</details>
