### ISSUE TITLE
[1.1.1] Finding Questions

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#3]
<details><summary>Task Title ID</summary>
<p>

#3

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`Finding as many questions for the client that will be cut down and be prioritised so that we can understand the client requirements and company better.`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Able to find questions to discuss the requirements with the clients`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Come up with relevant questions for the meeting with the client`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`4 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`29/08/2023` - `01/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [x] Den

- [x] Hakim

- [x] Zac

- [x] Brendan

- [x] Rudhi

- [x] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`Complete`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`Low priority`

</p>
</details>

**Comment by bren37** [comment]
<details><summary>Work Done</summary>
<p>
- Is each driver assigned to only a particular van ?
- It was mentioned that the manager should be able to visualise the staff workload immediately on the landing page, how should the staff workload be visualise? (in chart, graph or calendar format with block of hours)
- Staff can indicate their job preference for the week, Can you clarify this?
- if the staff reject the job without informing the manager, would there be a notification given to the manager to notify them?
- For staffs that have over 40 hours of jobs allocated, will they still make available for job allocation or they should be flag out by the system?

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`29/08/2023` - `29/08/2023`

</p>
</details>

**Comment by Codestian** [comment]
<details><summary>Work Done</summary>
<p>

- Given all staff are given 7 days of annual leave, is there a limit to number of MCs and offs?
- Must bookings be done 1 week prior?

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`29/08/2023` - `30/08/2023`

</p>
</details>

**Comment by Cazyrah** [comment]
<details><summary>Work Done</summary>
<p>

- How does the process on workload allocation and planning work on a weekly basis?
- Any backup plans for unforeseen circumstances?
- Which features are crucial, and which are more flexible?
- Can you elaborate on how end-users will be able to request aircon services through the app? Will there be specific details they need to provide, and how will these requests be presented to the manager?
- It is mentioned that employees must inform their availability by Wednesday for the upcoming week's planning. How will the system handle late submissions or changes in availability after the deadline?
- For IT administrators overseeing user management, could you provide more details on what tasks they would handle? Will they also have visibility into workload data?

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`29/08/2023` - `30/08/2023`

</p>
</details>

**Comment by rudhifnd** [comment]
<details><summary>Work Done</summary>
<p>

1. The app should be Web-based in a language of your choosing
-> Does the website have to be mobile friendly, or are you strictly using it on a computer?

2. The manager should be able to visualise the staff workload immediately on the landing page
-> How do you want it visualised on the landing page? (By staff, by date/time/calendar, by workload)
-> What kind of information to show along with workload? (Staff name, type, timing)
-> How to visualise workload for each staff type? (Driver, technician)

3. The manager should be able to allocate jobs to staff for one week at a time
-> Can this be edited later on? 
-> How are jobs allocated? By hours? Per location? 

4. The manager should be able to view up to three staff availability and any relevant information
to make the job assignment easier on the job allocation page
-> What is the relevant information?
-> What kind of staff? (Driver, tech)
-> How easy? What makes allocating a job easier?
-> Is staff availability and job allocation on the same page?

8. Staff can add and edit their availabilities up to 5 weeks ahead of time.
-> Will staff be able to see other the availabilities of other staff? Should they be able to see? If so, can driver see tech availability?
-> How many days before actual day can staff edit? (e.g. cannot edit 3 days prior)

9. Staff can indicate their job preference for the week
-> Will staff be able to see if others prefer a job? Should they be able to see?

10. Staff can reject jobs assigned to them, but they will be warned to discuss the jobs with their
manager before proceeding with the rejection
-> Upon rejecting, will manager be informed about it?
-> How many days before actual day can staff reject? Can reject on the week itself?

11. The company’s IT administrators will oversee adding new staff and managers to the system
-> Is this the on the same web page?

`OTHER QUESTIONS
`
- How do you want each staff member to be identified during login?
- What if for a specific day, M Electric tech has to do 5, Dicon only has to do 1.  How exactly do you allocate who goes to which van?
- Do you plan according to location, aircon brand?
- What is the entire process of obtaining a "job" from a client?
- What if not all technicians are needed for that day? (Slow day, not much servicing to do)
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`30/08/2023` - `31/08/2023`

</p>
</details>

**Comment by malcolmkzh** [comment]
<details><summary>Work Done</summary>
<p>

- How long does van servicing take?
- What is their current system and do you wish to migrate?
- How many managers ?
- Will the website be intranet or internet ?

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`31/08/2023` - `31/08/2023`

</p>
</details>

**Comment by DeNhAiKal** [comment]
<details><summary>Work Done</summary>
<p>

1. Prior to this, what are the constraint you have when making the schedule?
2. For your company, are the managers the admin for the new scheduling website? If not, who will be the admin users?
3. Do you want only one admin(manager) account or unique accounts for different admin(manager)? Means all managers will use the same log in credentials.

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`31/08/2023` - `31/08/2023`

</p>
</details>
