### ISSUE TITLE
[2.1.1] Project scope changes

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#30]
<details><summary>Task Title ID</summary>
<p>
#30
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`After reviewing will update the project scope changes in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Update the board with the project scope changes if necessary`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`New project scope changes are established`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`1 day`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`22/10/23` - `22/10/23`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [x] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`To Do`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by bren37** [comment]
<details><summary>Work Done</summary>
<p>

Product Scope 

There are no changes in the product scope. The scope of the product is a web application for the aircon retailer company to streamline and optimize their work allocation process for the manager and staff. The purpose is to provide the manager an overview visualisation of the staff workloads, allowing them to allocate jobs to the staff per week. It prioritizes workload efficiency by highlighting low workload and high workload staff.

The product allows staff to plan their availability up to 5 weeks in advance and their job preferences which helps the manager to plan based on availability and job preferences effortlessly. Overall, the product’s scope is to improve job allocation within the aircon retailer company. 

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`22/10/2023` - `22/10/2023`

</p>
</details>
