### ISSUE TITLE
[2.1.4] Updated use case description

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#33]
<details><summary>Task Title ID</summary>
<p>
#33
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`After reviewing will update the use case description in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Update the board with the use case descriptionchanges if necessary`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`New use case description changes are established`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`1 day`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`22/10/23` - `22/10/23`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [ ] Brendan

- [x] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`To Do`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by rudhifnd** [comment]
<details><summary>Work Done</summary>
<p>



![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/10296163-99c5-4bca-8aed-0717757785e9)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/aabd84e9-f8fa-4f92-8d60-bafd657325e3)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/8c6d450d-e064-4615-9cfd-22b16c08da0b)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/d5ecb9f0-74c3-4490-b462-3e62ccb124e4)



</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`22/10/23` - `22/10/23`

</p>
</details>
