### ISSUE TITLE
[3.1] Justify the architecture design

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#37]
<details><summary>Task Title ID</summary>
<p>
#37
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`Create and justify the architecture design`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Justification is in the kanban board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Clear justification for the design`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`4 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`31/10/2023` - `3/11/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [x] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`To Do`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by bren37** [comment]
<details><summary>Work Done</summary>
<p>

Hierarchical - Layered Architecture
The chosen hierarchical - layered architecture is exceptionally well-suited for the project, aimed at developing an interactive web-based workload management system to replace the existing spreadsheet system. This architecture provides a systematic and organized approach to handling the various components of the system. The rationale for selecting this architectural design are:

1. Scalability
As the workload management system evolves, new layers or components can be added to handle additional features or functionalities. This allows for scalability as the company’s workload and resource management needs grow.

2. Clear separation of concerns
The project involves multiple aspects such as user interaction(UI), business logic, data processing and database operations. The 
layered architect excels at organizing and managing these distinct functionalities.

3. Modularity and maintainability 
The project’s goal of replacing the existing spreadsheet system with an interactive web-based workload management system aligns with the modularity and maintainability benefits of a layered architecture. Each layer can be developed, tested and maintained independently.

4. Security and data protection
Security measures can be implemented at specific layers ensuring the protection of sensitive information related to workload management and job progress tracking.

5. Flexibility for future enhancements
If there is a need to extend the system’s capabilities, the layered architecture allows for the addition of new layers or components without major disruptions to the existing functionality

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/2c8e0f29-9d57-4c82-abf6-ee31a2947589)

Figure 1: Hierarchical - Layered Architecture Diagram

1. Presentation layer
Responsible for handling user interaction and displaying information to the user through a web interface. Boundary classes are in this layer. They manage input and output, acting as a bridge between the user interface and the underlying system components. Placing the boundary classes in the presentation layer aligns the role in handling user interactions, displaying information and receiving user input. Thereby encapsulate the presentation logic and communicate user actions to the rest of the system.

2. Business logic layer
Contains the application’s logic and rules. It processes data received from the presentation layer and prepares it for the interaction with the data access layer. Control classes are in this layer. They contain the application business logic, process user input received from the boundary classes, make decisions based on that input and interact with the data access layer to retrieve or modify data as needed. Placing control classes in the business layer ensures that the core logic of the application, decisions, and validations is centralized and separated from both the user interface and data storage. This separation of concerns enhances maintainability, scalability, and reusability of the application.

3. Data access layer
Manages communication with the database, performing operations such as querying , updating and deleting the data. Entity classes are in this layer. Entity classes represent the business data entities within this application. They encapsulate the data structure and behaviors associated with specific entities in the domain. Placing entity classes in the data layer ensures a clear separation between the representation of data and business logic of the application. The data layer is responsible for interacting with the database to persist and retrieve data.


</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`31/10/2023` - `3/11/2023`

</p>
</details>
