### ISSUE TITLE
[3.2] Justify the detailed design

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#38]
<details><summary>Task Title ID</summary>
<p>
#38
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`Create and justify the detailed design`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Justified detailed design`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Clear justification`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`5 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`3/11/2023` - `8/11/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [x] Zac

- [ ] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`To Do`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`Medium priority`

</p>
</details>

**Comment by Cazyrah** [comment]
<details><summary>Work Done</summary>
<p>

Factory pattern
The factory pattern is suitable for creating objects of related types without specifying the exact class of object that will be created. In this project, using the factory pattern to create different types of staff(driver and technicians) allows for flexibility in adding new types of staff in the future without modifying existing codes. The rationale for selecting this pattern are:

Staff - Types of staff role
There are currently 2 main staff types, technicians and drivers. By  using the factory pattern, will be able to encapsulate the process of creating specific types of staff for the different roles. This promotes code reusability and ensures that the correct type of staff is created based on the role.
Scalability for future brands
The factory pattern separates staff construction code from the code that uses the staff object. If the company decides to add new types of employees in the future, the factory pattern provides a flexible structure to add new staff without modifying the existing code extensively. For example, to add a new staff type, engineers will only need to change the StaffFactory.
Simplified client code
The client code that needs to create staff can do so through a generic ‘staffFactory’, without being concerned about the specific staff role. This simplifies the client’s interaction with the staff creation process.

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/48308492/9b2f70a9-1241-4307-909e-0d4659d16037)

Figure 2: Factory Pattern implementation based on class diagram

The Factory Pattern is evident in the user creation implementation, particularly within the StaffRegistration class. The staffRegistration class creates a staffFactory, which is designed to instantiate different types of staff, such as technicians or divers, encapsulating the intricacies of object creation within a centralized component.
The technician and driver entities implement the Istaff which can be useful to other classes such as the manageLeaveRequest class. For instance, the ManageLeaveRequest class can seamlessly interact with diverse staff entities through the standardized IStaff interface.
The utilization of the Factory Pattern, coupled with the common interface, not only ensures code consistency but also sets the stage for enhanced maintenance and future extensibility. Modifications or additions to staff entities can be localized to the StaffFactory, minimizing the impact on other parts of the system and adhering to best practices in design patterns.

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/48308492/bc4d8124-fd8b-4791-bffe-ab5392772bf8)

Figure 3: Implementation without factory pattern class diagram

The Factory Pattern is a valuable design pattern, especially when dealing with multiple types of staff entities. Without its implementation, creating different staff types would require the client-side code to explicitly specify the class to instantiate. This approach results in a cumbersome process, demanding extensive modifications to the client code each time a new staff type is introduced. However, by incorporating the Factory Pattern, the instantiation logic is encapsulated within a dedicated factory class. Consequently, the client code only interacts with the factory to create staff objects, shielding it from the intricacies of class instantiation. This separation of concerns not only enhances code organization but also streamlines the addition of new staff types. With the Factory Pattern, adapting to changes merely involves adjusting the factory class, minimizing the need for extensive modifications in the client code and promoting a more modular and maintainable codebase



Observer pattern
The observer pattern is useful for establishing a one-to-many dependency between objects, where one object(the subject) maintains a list of its dependents(observers) and notifies them of state changes. In this project, the observer pattern can be applied to notify relevant stakeholders (e.g managers, staff) about changes in job assignments, leave requests, and rejecting jobs. This promotes real-time updates and effective communication within the system.The rationale for selecting this pattern are:

Real - time updates and notifications
The workload management system requires real-time updates on job assignments and progress tracking. By implementing an observer pattern, it is able to establish a mechanism for notifying relevant components(observers) whenever there are changes in the system. This ensures that stakeholders receive timely information.

Decoupling of components
The observer pattern decouples the subject(e.g. manager) from its observers(e.g. staff). This promotes a more modular and maintainable design, where changes to one component do not directly impact others. It also allows for easy addition or removal of observers.

Flexible handling of events
As the workload management system evolves, there may be a need to introduce new types of events or notifications. The observer pattern provides a flexible framework to extend and handle various types of events without modifying the core subject logic.

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/48308492/dba42496-49db-4285-8dc2-3e90ae540029)

Figure 4: Observer Pattern implementation based on class diagram

The Observer Pattern is crucial in optimizing communication and facilitating real-time updates within the workload management system. This particular design pattern sets up a one-to-many relationship between objects, creating a mechanism for efficient dissemination of information. In the context of our system, the job entity class serves as the subject, utilizing the abstract subject component. The abstract subject allows the job entity class to attach observers, enabling them to receive notifications when specific methods are called within the job entity class. This dynamic interaction ensures that staff stay informed about changes in job assignments, ensuring that they receive prompt and real-time information on updates in the system.

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/48308492/2d0348b3-f1ba-40f7-bde5-81bb93a57dd8)

Figure 5: Implementation without Observer pattern class diagram

The Observer Pattern plays a crucial role in enabling real-time communication and updates within the workload management system. Without the Observer Pattern, the job entity class would face the challenge of directly notifying observers, leading to a complex and tightly coupled system. However, with this pattern, the code gains clarity, organization, and modularity. Observers would adapt to system changes without intricate modifications to the core job entity class. Similar to the way the Factory Pattern optimizes staff entity creation, the Observer Pattern enhances the overall design, ensuring efficient communication and maintainability in the dynamic workload management environment.

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`3/11/2023` - `18/11/2023`

</p>
</details>
