### ISSUE TITLE
[1.2.2] Functional Requirements

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#4]
<details><summary>Task Title ID</summary>
<p>
#4
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Details</summary>
<p>

` Create a functional requirements that will capture the intended behavior of the system. Should describe the user requirements in details.`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Goals</summary>
<p>

`Able to come up with the completed functional user requirements for the client`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Success - Completion Details:</summary>
<p>

`Clear and precise functional user requirements in details to be updated in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`2 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`11/09/2023` - `12/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [ ] Brendan

- [ ] Rudhi

- [x] Malcolm 
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by malcolmkzh** [comment]
<details><summary>Work Done</summary>
<p>

### **Registration**
- The IT administrator can modify accounts. 
- The IT administrator can view accounts.
- The IT administrator can add accounts.
  -   Information to include:
      - Name
      - Username
      - Password
      - Privileges
- The IT administrator can delete accounts. 
- IT administrator/manager can restore a backup account.
- The system will validate the account availability.


### **Login**
- The user will login using their username and password.
- The system must validate that both fields have been filled up.
- The system must validate that the username and password are correct.
- If the login information is incorrect, the system will display an error message.
- The system will redirect users to the landing page.

### **Applying Leave**
- Staff are able to submit requests for annual leave.
  - Information to include:
    - Date
    - Reason
- System will display current and previous leave requests applied by staff with status.
  - Status includes:
    -   Approve
    -   Reject
    -   Pending
- System will display pending and previous leave requests by staff to the manager.
- Managers must be able to approve or deny pending leave requests.
- System will display staff remaining leaves available for the year.


### **Vehicle Status**
- The manager and driver will be able to view the vehicle status and information.
  - Status includes:
    - Servicing
    - Operable
  - Information includes:
    - Vehicle Number
    - Vehicle Model
- Manager and driver must be able to edit the vehicle status and information.
- Manager must be able to add in a new vehicle.
- Manager must be able to delete the vehicle.


### **Manager - Assigning/Adding Jobs**
- The manager must be able to add jobs to be fulfilled in the calendar.
- The system must display a calendar view of the jobs available.
  - Job Specification Include
    - Location
    - Time
    - Brand
    - Service Type
- The manager must be able to assign staff members to jobs.
- The system should retrieve staff in order of their preference when assigning jobs.
- The system must display the staff assigned to the job.
- The system must display the staff workload history based on hours
- The manager must be able to add back-up staff for the week.


### **Manager - Finalize weekly Jobs**

- The manager should be able to finalize the weekly schedule.
- The system will only allow the manager to finalize the following week schedule on the current week Thursday to Sunday.
- The system will notify staff members of the finalized weekly schedule after the manager finalize it.


### **Staff - Add job preference**
- System will display a calendar that can view up to 5 weeks ahead of time.
- Staff will be able to include their preference on the days they want to work.
  - Options to choose
    - Full Day
    - Half Day (AM)
    - Half Day (PM)
- System will prevent editing of job preferences up until the following the Sunday every Wednesday.


### **Staff - View jobs assigned**
- System will display a calendar view of all the jobs available.
- Staff can request to highlight the jobs assigned to them.
- Staff can view job details for a selected job.
  - Details to show:
    - Workers assign to job
    - Date of job
    - Time of job
    - Location of Job
    - Type of Job
- System will display a reject button for the assigned staff.


### **Staff - View finalized weekly jobs assigned**
- System will display a list view of the jobs assigned to the staff for the week.
  - Job information include:
    - Location
    - Date
    - Time
    - Aircon Brand
    - Type of service





</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`11/09/2023` - `12/09/2023`

</p>
</details>
