### ISSUE TITLE
[3.4] Conduct White box testing

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#41]
<details><summary>Task Title ID</summary>
<p>
#41
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`Plan and conduct the white box testing`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Pseudocode and CFG is done correctly.`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Pseudocode and CFG in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`5 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`10/11/2023` - `15/11/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [ ] Brendan

- [x] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`To Do`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by rudhifnd** [comment]
<details><summary>Work Done</summary>
<p>



![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/58a22b7b-b971-46a4-8349-946c03007f4b)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/00a77de7-d520-4eed-9d0a-bea6ce42994e)



</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`10/11/2023` - `15/11/2023`

</p>
</details>
