### ISSUE TITLE
[3.5.1] IT Administrator Prototype/Wireframe

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#44]
<details><summary>Task Title ID</summary>
<p>
#44
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`Create the Webpages wireframe for the IT administrator side`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`IT administrator wireframe is done`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`IT administrator wireframe is on the board `

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`3 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`13/11/2023` - `16/11/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [ ] Brendan

- [ ] Rudhi

- [x] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`To Do`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by malcolmkzh** [comment]
<details><summary>Work Done</summary>
<p>


![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/25952539/59748a9f-5f0a-4993-81a8-bd13fc1a8d50)



![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/25952539/f7c4ae0a-5ae3-41af-b37a-5325a2e84e02)




![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/25952539/778a957a-21fb-4e46-ab17-242b9a33919c)




![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/25952539/eb935c3d-f92c-455b-ac0f-960a6308d043)



![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/25952539/d16338e6-5c49-4ddc-a4c3-19c33b720298)



![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/25952539/568d0e9c-3db0-41c3-a5bf-836ccae879cf)



![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/25952539/4ad9778b-1897-4f58-8777-47f856c46a9d)



</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`13/11/2023` - `16/11/2023`

</p>
</details>
