### ISSUE TITLE
[3.5.2] Staff Prototype/Wireframe

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#45]
<details><summary>Task Title ID</summary>
<p>
#45
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`Create the Webpages wireframe for the Staff side`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Staff wireframe is done`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Staff wireframe is on the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`3 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`13/11/2023` - `16/11/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [ ] Brendan

- [x] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`To Do`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by rudhifnd** [comment]
<details><summary>Work Done</summary>
<p>

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/4cdd033a-65db-478c-8fa8-b9b859e31216)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/5dd062aa-fd0c-4b92-9305-ea834761f871)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/6d862c53-bfca-4e72-963f-b22078f5d957)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/35b9f192-d887-4600-87f5-042e319dfa32)

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`13/11/2023` - `16/11/2023`

</p>
</details>
