### ISSUE TITLE
[3.5.3] Manager Prototype/Wireframe

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#46]
<details><summary>Task Title ID</summary>
<p>
#46
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`Create the Webpages wireframe for the Manager side`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Manager wireframe is done`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Manager wireframe is on the board `

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`3 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`13/11/2023` - `16/11/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [x] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`To Do`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by bren37** [comment]
<details><summary>Work Done</summary>
<p>

<ins>View Staff Workload</ins>

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/d84d68c2-0c58-4667-af81-f5b491b1dd82)

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/6a27b4f8-0b05-4d54-b5f4-2fee2db003c1)

This is the manager landing page whereby the manager is able to view all the individual staff workload. There is a dashboard at the bottom of the page for staff to click on to view the staff workload. Red borders indicate underwork(<40 hours), yellow indicates borderline acceptable working hours and green indicates more than 40 hours working hours.

<ins>View Staff Preference/ Availability</ins>

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/d1f20b53-a4be-42bb-9ea1-2857aea4afc0)

Manager can click on the yellow coloured jobs to view the staff’s preference and availability in detail.

<ins>Add jobs</ins>

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/61b936fe-af5e-49bf-947d-47fd0425b309)

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/2943a8af-91ab-4a32-abfd-66b0bfd74b1b)

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/8d1164fc-f10b-47f9-bb36-d2d71a99194b)

To create a new job, the manager can click on the “+” icon. This will bring the manager to adding a new jobs page. Fill in the required details,submit and confirm the details to successfully add a new job.

<ins>Assign staff to Jobs</ins>

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/c7082ea5-015f-4756-9973-3d24178b3493)

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/e839c1a0-8669-407f-8754-ccac6eff7b6d)

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/10a142a7-b12a-42d9-9136-9887fee022ad)

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/798a1581-80ba-4147-995e-2684bfcfcf06)

Manager can click on the checklist icon at the navigation bar to proceed to view all current jobs details and this page will allow the manager to allocate staff to jobs. In this current jobs page, the manager will be able to view all the details pertaining to the job. There will be a “+” at each of the jobs, this will be where the manager can allocate staff. Select the technician and driver of choice in the drop down list. In this dropdown list the system will automatically place the most suitable staff at the top of the list with reference to the availability, preference and brand of the staff. Manager will not require to view preference/availability in the calendar view. After selecting and submitting, the system will notify the manager that the job has been allocated successfully.

<ins>Accept rejecting jobs request</ins>

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/2f4436b6-cecd-405d-bc0e-493576251e75)

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/cf03be5c-5808-4363-8168-16f00d4638eb)

To manage the rejected request jobs, the manager can click on the reject tab and view all the requests. In this page, the manager can view the details of jobs and by clicking on the cross button will be able to view the name and reason to reject this job. There will be an accept or reject button for the manager to choose from.

<ins>View Vehicle</ins>

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/ff276635-bdc5-44e9-b331-9af6ab8cf7e4)

To view all vehicle status, the Manager can click on the van icon in the navigation menu. In this page, the manager is able to read and amend the vehicle details.

<ins>Accept leave request</ins>

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/476c7b33-4f38-4ee5-a57d-b3f6f846cd47)

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/122149034/bdef8c9f-ab82-4dde-bea6-98cd064c1221)

To manage the leave request, the manager can click on the clock icon. In this page the manager will be able to view all the leave request details and accept or reject the request by clicking on the respective icon of tick and cross.

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`13/11/2023` - `16/11/2023`

</p>
</details>
