### ISSUE TITLE
[1.3.1] Use Case diagram

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#5]
<details><summary>Task Title ID</summary>
<p>
#5
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Details</summary>
<p>

` Create the use case diagram to visually represent the different ways that a system interacts with actors.`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Goals</summary>
<p>

`Able to come up with the completed use case diagram to aid understanding our concepts and show how the system interacts with the actors.`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Success - Completion Details:</summary>
<p>

`Clear and precise use case diagram in details(In a image) to be updated in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`4 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `17/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [ ] Brendan

- [ ] Rudhi

- [x] Malcolm 
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by malcolmkzh** [comment]
<details><summary>Work Done</summary>
<p>

![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/25952539/b398886f-1be6-4c9f-b22c-4c05e4cf4b95)

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`13/09/2023` - `14/09/2023`

</p>
</details>
