### ISSUE TITLE
M1 Retrospection

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#51]
1. What are the great things that your team is doing?
2. Are there any thing in the team that wish could be changed?
3. Do you have ideas that could improve the current situation of your team?
4. As a leader, do the members of the team know the issues you face?
5. What went well in Milestone ONE?
6. What could be improved?
Team dynamics, team management, task allocation and management, etc.
7. What will we commit to improve in the next milestone?

**Comment by Codestian** [comment]
1. What are the great things that your team is doing?
- Follow the tasks provided and complete them before deadline.

2. Are there any thing in the team that wish could be changed?
- Not at the moment.

3. Do you have ideas that could improve the current situation of your team?
- No ideas at the moment.

4. As a leader, do the members of the team know the issues you face?
- No.

5. What went well in Milestone ONE?
- Being able to deliver the requirements as stated. 

6. What could be improved? Team dynamics, team management, task allocation and management, etc.
- Clarify with each team member on whether the task has any minor issues.

7. What will we commit to improve in the next milestone?
- Always clarify whenver there are doubts.

**Comment by malcolmkzh** [comment]
1. Everybody does their respective job
2. NO
3. NO
5. We submitted and do our own task on time.
6. NO
7. Better quality of work

**Comment by DeNhAiKal** [comment]
1. What are the great things that your team is doing?
- Able to complete the tasks according to the dateline I set for the team. 

2. Are there any thing in the team that wish could be changed?
- NIL

3. Do you have ideas that could improve the current situation of your team?
- NIL

4. As a leader, do the members of the team know the issues you face?
- Trying coordinate with each other 

5. What went well in Milestone ONE?
- What went well is the coordination of team

6. What could be improved?
- Team Management 

7. What will we commit to improve in the next milestone?
-Allocating the task appropriately

**Comment by rudhifnd** [comment]
1. What are the great things that your team is doing? Work organisation and delegation is very thorough
2. Are there any thing in the team that wish could be changed? No
3. Do you have ideas that could improve the current situation of your team? No
4. As a leader, do the members of the team know the issues you face? NA
5. What went well in Milestone ONE? Everyone submitted high quality work on time.
6. What could be improved? Better communication
8. What will we commit to improve in the next milestone? Better communication among each other

**Comment by Cazyrah** [comment]
1. What are the great things that your team is doing?
- The team is able to collaborate effectively and focus on their specific tasks.
2. Are there any thing in the team that wish could be changed?
- None
3. Do you have ideas that could improve the current situation of your team?
- None
4. What went well in Milestone ONE?
- The team is clear of the project scope, and M1 presenters were able to answer all of the questions.
5. What could be improved? (Team dynamics, team management, task allocation and management, etc.)
- Current management is acceptable.
6. What will we commit to improve in the next milestone?
- Accuracy of work delivered.

**Comment by bren37** [comment]
1. What are the great things that your team is doing?
- Constant meeting with the team to have to clear understanding of the milestone and not miss the deadline.

2. Are there any thing in the team that wish could be changed?
- Some deadline could be extended.

3. Do you have ideas that could improve the current situation of your team?
- No
4. As a leader, do the members of the team know the issues you face?
- NIL

5. What went well in Milestone ONE?
- Everything went according to plan.

6. What could be improved?        
Team dynamics, team management, task allocation and management, etc.
- Team management.

 7. What will we commit to improve in the next milestone?
 - Better quality of work delivered.
