### ISSUE TITLE
[2.4] Design the sequence diagram

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#52]
<details><summary>Task Title ID</summary>
<p>
#52
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`Design and create the sequence diagram after the discussion`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Sequence diagram is design properly, clear and concise`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Sequence diagram are established in the project board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`4 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`23/10/23` - `26/10/23`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [ ] Brendan

- [x] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`To Do`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by rudhifnd** [comment]
<details><summary>Work Done</summary>
<p>



![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/69d076ea-7da1-4018-941b-c6f802688e92)
![Image](https://github.com/DeNhAiKal/INF2001_P5-5/assets/58452867/9b34f666-0bf7-420b-9205-1361ae5cf79c)



</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`23/10/2023` - `26/10/2023`

</p>
</details>
