### ISSUE TITLE
[1.4.3] Software Estimation

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#6]
<details><summary>Task Title ID</summary>
<p>
#6
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

` Estimate the size of the project, manpower and time required. Explain the parameters you have chosen for the estimation.`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Able to come up with a detailed estimation for the client`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Clear and precise software estimation in details to be updated in the board`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`3 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `17/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [x] Zac

- [ ] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`High priority`

</p>
</details>

**Comment by Cazyrah** [comment]
<details><summary>Work Done</summary>
<p>

ESTIMATION OF SIZE - USE CASE POINTS

ID: UC-1
Name: Access The System
Description: User attempts to access the system by providing their username and password
Primary Actor: User
Preconditions: None

Main Success Scenario:
1.	User navigates to the system's login page.
2.	User enters their username and password.
3.	User submits the information.
4.	System checks that both the username and password fields are filled.
5.	System checks the validity of the username and password.
6.	System redirects the user to the system's landing page.
Alternative Scenarios:
4a.	Username or password field is empty.
	4a1. System displays an error message indicating that both fields are required.
5a.	Username or password is incorrect.
	5a1. System displays an error message indicating the invalid login information.
	5a2. User is given the option to retry
Post conditions: 
Main: User has successfully logged into the system and is on the landing page.
4a.	Username or password field is empty.
5a.	Username or password is incorrect.
Priority: High

ID: UC-2
Name: Create System Accounts
Description: IT administrator accesses the system to create a new user account, specifying user information and privileges.
Primary Actor: IT administrator
Preconditions: IT Administrator is logged into the system.
Main Success Scenario:
1.	IT Administrator navigates to the Account Creation section.
2.	System displays a form for creating a new user account.
3.	IT Administrator enters the required user information, including name, username, password, and privileges.
4.	IT Administrator submits the account creation form.
5.	System validates the information and creates the new user account.
6.	System displays a confirmation message.
Alternative Scenarios:
4a.	Required user information is missing or invalid.
	4a1. System displays an error message indicating the missing or invalid information.
5a.	Account with the specified unique field already exist.
	5a1. System displays an error message indicating that the account with the specified unique field already exist.
	5a2. IT Administrator is given the option to modify the specified information, or discard the form for creation.
Post conditions: 
Main: IT Administrator has successfully created a new user account with the specified information and privileges, and the new account is now available in the system.
Priority: High

ID: UC-3
Name: Modify Existing Accounts
Description: IT administrator accesses the system to modify existing user accounts
Primary Actor: IT administrator
Preconditions: IT Administrator is logged into the system.
Main Success Scenario:
1.	IT Administrator navigates to the account modification section.
2.	System displays a list of user accounts.
3.	IT Administrator selects a specific user account from the list for modification.
4.	System displays the user account details, including name, username, and privileges.
5.	IT Administrator makes necessary modifications to the user account.
6.	IT Administrator saves the changes.
7.	System updates the user account information and displays a confirmation message.
Alternative Scenarios:
2a.	No user accounts are available for modification.
	2a1. System displays a message indicating that there are no user accounts available for modification.
	2a2. IT Administrator is given the option to add accounts
6a.	IT Administrator decides not to save the changes.
	6a1. System discards the modifications.
Post conditions: 
Main: IT Administrator has successfully modified a user account, and the updated information is saved in the system.
Priority: High

ID: UC-4
Name: Manage Job Preference
Description: Staff sets their job preferences for the upcoming weeks
Primary Actor: Staff
Preconditions: Staff is logged into the system
Main Success Scenario:
1.	Staff navigates to the job preference section.
2.	System displays a calendar showing the upcoming weeks.
3.	Staff selects a week to set their preferences.
4.	Staff indicates the preferred day, time, location and type of service for the week.
5.	Staff submits their preferences.
6.	System stores the preferences and displays a confirmation message.
Alternative Scenarios: -
Post conditions: 
Main: Staff has successfully set their job preferences for a specific week.
Priority: Low

ID: UC-5
Name: Submit Leave Request
Description: Staff submits a request for annual leave, specifying the date and reason for the leave
Primary Actor: Staff
Preconditions: Staff is logged into the system

Main Success Scenario:
1.	Staff navigates to the leave request section.
2.	System displays a form for leave request.
3.	Staff enters the date for the requested leave.
4.	Staff provides a reason for the leave request
5.	Staff submits the leave request.
6.	System records the request and displays a confirmation message.
Alternative Scenarios:
5a.	Date field is empty or invalid.
	5a1. System displays an error message indicating that a valid date is required.
5b.	Staff does not provide a reason for the leave request.
	5b1. System displays an error message indicating that a reason is required.
5c.	Staff have insufficient annual leave.
	5c1. System displays an error message indicating that the staff have insufficient annual leave.
Post conditions: 
Main: Staff has successfully submitted a leave request, and the request is recorded in the system.
5c.	Staff have insufficient annual leave, and the request is voided.
Priority: Low

ID: UC-6
Name: Accept Leave Request
Description: Manager reviews the leave requests requested by staff members, and accepts it.
Primary Actor: Manager
Preconditions: Manager is logged into the system.

Main Success Scenario:
1.	Manager navigates to the leave request management section.
2.	System displays a list of pending leave requests from staff members.
3.	Manager accepts a specific leave request of a staff member.
4.	System updates the leave request status and notifies the staff member.
5.	System displays a confirmation message.
Alternative Scenarios:
2a.	No pending leave requests are available.
	2a1. System displays a message indicating that there are no pending leave requests.
3a.	Manager decides to deny the request.
	3a1. System updates the leave request status and notifies the staff member.
3b.	Manager decides to leave the request pending.
	3b1. Manager can choose to review other leave requests.
Post conditions: 
Main: Manager has successfully reviewed leave requests by staff members, the request status is updated in the system, and staff members are notified of the request status.
Priority: High

ID: UC-7
Name: View Vehicle Status
Description: Manager or Driver accesses the system to manage vehicle status and information
Primary Actor: Manager, Driver
Preconditions: Manager or Driver is logged into the system

Main Success Scenario:
1.	Manager or Driver navigates to the Vehicle Status Management section.
2.	System displays a list of available vehicles along with their status, vehicle numbers, and vehicle models.
3.	Manager or Driver selects a specific vehicle from the list to modify the information.
4.	System displays the vehicle details, including vehicle number, vehicle model, and status.
5.	Manager or Driver makes necessary modifications to the vehicle information or status, and submits the changes.
6.	System updates the vehicle information and status, and displays a confirmation message.
Alternative Scenarios:
2a.	No vehicles are available in the system.
	2a1. System displays a message indicating that there are no vehicles available.
	2a2. Manager is given the option to add new vehicles.
5a.	Manager or Driver decides not to save the changes.
	5a1. System discards the modifications.
Post conditions: 
Main: Manager or Driver has successfully updated the vehicle information, and details are saved in the system.
Priority: High

ID: UC-8
Name: Create Workload Draft
Description: Manager views the available jobs, select a job, view staff preference, assigns job to staff, and save the draft
Primary Actor: Manager
Preconditions: Manager is logged into the system
Main Success Scenario:
1.	Manager navigates to the Workload Management section.
2.	System displays the list of available jobs for assignment.
3.	Manager selects a specific job from the list.
4.	System displays a calendar showing the upcoming days.
5.	Manager selects a specific day.
6.	System displays the available staff and their preference. 
7.	Manager assigns the selected job to one or more staff members.
8.	Manager saves the draft of the workload.
9.	System displays a confirmation message.
Alternative Scenarios:
2a.	No available jobs for assignment.
	2a1. System displays a message indicating that there are no available job.
6a.	No available staff for the job.
	6a1. System displays a message indicating that there are no available staff for the job.
8a.	Manager decides not to save the draft.
	8a1. System discards the draft.
8b.	Manager decides to assign more jobs.
	8b1. Repeat steps 2 – 8.
Post conditions: 
Main: Manager successfully created a draft of the workload.
Priority: High

ID: UC-9
Name: Manage Backup Staff
Description: Manager adds backup staff on Workload Draft
Primary Actor: Manager
Preconditions: Manager is logged into the system, and a workload draft exists
Main Success Scenario:
1.	Manager navigates to Workload Draft Backup section.
2.	System displays a list of existing Workload Drafts.
3.	Manager selects a specific Workload draft.
4.	System displays a calendar indicating the Workload Draft
5.	Manager selects a specific day.
6.	System displays a list of the available backup staff and their preference. 
7.	Manager assigns the selected job to one or more available backup staff members.
8.	Manager saves the draft of the workload.
9.	System displays a confirmation message.
Alternative Scenarios:
6a.	No available staff members to assign as backups.
	6a1. System displays a message indicating that there are no available staff members to assign as backups.
8a.	Manager decides not to save the draft.
	8a1. System discards backup for the workload draft.
Post conditions: 
Main: Manager successfully assigned backup staff to a workload draft.
Priority: Medium

ID: UC-10
Name: Manage Job Schedule
Description: Staff views their weekly job assignments, select a job, and accept it
Primary Actor: Staff
Preconditions: Driver or Technician is logged into the system
Main Success Scenario:
1.	Staff navigates to their weekly job assignments.
2.	System displays a list of jobs assigned to the staff.
3.	Staff selects a specific job from the list.
4.	Staff accepts the selected job.
5.	System updates the job status and displays a confirmation message.
Alternative Scenarios:
3a.	No jobs assigned to the staff.
	3a1. System displays a message indicating that there are no jobs assigned yet.
4a.	Staff declines the job.
	4a1. System updates the job status as declined.
	4a2. System issues a warning message.
Post conditions: 
Main: Staff successfully accepted their assigned job.
4a.	Staff declines the job.
Priority: High

ID: UC-11
Name: Modify Workload Draft
Description: Manager reviews a workload draft, checks for job assignment status for staff members, and finalizes the workload for the week.
Primary Actor: Manager
Preconditions: Manager is logged into the system, and a workload draft exists
Main Success Scenario:
1.	Manager navigates to the Workload Management section. 
2.	System displays the list of existing workload drafts. 
3.	Manager selects a specific workload draft from the list for review. 
4.	System displays the draft, including assigned jobs, dates, staff members, and job assignment status.
5.	Manager finalizes the workload draft for the week.
6.	System updates the workload status and notifies staff members.
7.	System displays a confirmation message.	
Alternative Scenarios:
2a.	No existing workload draft are available.
	2a1. System displays a message indicating that there are no workload draft available.
5a.	Manager decides to delete the draft.
	5a1. System displays a message indicating the successful deletion of the draft.
5b.	Manager decides to not to finalize the draft.
	5b1. System returns to display existing workload drafts.
        5b2. Manager may choose to review other drafts.
6a.	Staff members have not accepted some assigned jobs.
	6a1. System displays a warning message indicating which jobs are pending staff acceptance.
	6a2. Manager may choose to reassign pending jobs, or still proceed to finalize the draft.
	6a3. System displays a confirmation message.
Post conditions: 
Main: Manager has successfully reviewed, and finalized a workload draft for the week. Staff members are notified of the workload status.
Priority: High

USE CASE TRANSACTIONS COMPLEXITY:
Use Case Complexity | Number of Transactions | Weight
Simple | <= 3 | 5
Average | 4 – 7 | 10
Complex | > 7 | 15

Use Case ID | Number of Transactions | Use Case Complexity | Weight
UC-1 | 3 | Simple | 5
UC-2 | 4 | Average | 10
UC-3 | 5 | Average | 10
UC-4 | 2 | Simple | 5
UC-5 | 5 | Average | 10
UC-6 | 5 | Average | 10
UC-7 | 5 | Average | 10
UC-8 | 10 | Complex | 15
UC-9 | 6 | Average | 10
UC-10 | 5 | Average | 10
UC-11 | 9 | Complex | 15

Unadjusted Transactions Weight of all Use Cases:
Use Case Complexity | Weight | Number of Use Cases | Product of Weight and Number
Simple | 5 | 2 | 10
Average | 10 | 7 | 70
Complex | 15 | 2 | 30
Unadjusted Transactions Weight | - | - | 110

USE CASE ACTOR COMPLEXITY:
Actor Complexity | Weight
Simple | 1
Average | 2
Complex | 3

Unadjusted Actors Weight of all Use Cases:
Use Case ID | Number of Actors | Actor Classification | Weight
UC-1 | 1 | Simple | 1
UC-2 | 2 | Average, Complex | 2, 3
UC-3 | 1 | Complex | 3
UC-4 | 1 | Complex | 3
UC-5 | 1 | Complex | 3
UC-6 | 1 | Complex | 3
UC-7 | 2 | Complex | 3
UC-8 | 1 | Complex | 3
UC-9 | 1 | Complex | 3
UC-10 | 1 | Complex | 3
UC-11 | 1 | Complex | 3

Unadjusted Actors Weight of all Use Cases:
Use Case Actor Complexity | Weight | Number of Actors | Product of Weight and Actors
Simple | 1 | 1 | 1
Average | 2 | 1 | 2
Complex | 3 | 11 | 33
Unadjusted Actors Weight | - | - | 36

TOTAL UNADJUSTED POINTS (UUCW):
Unadjusted  Transactions  Weight+Unadjusted  Actors  Weight
=110+36
=146

TECHNICAL COMPLEXITY FACTORS:
Factor | Description | Weight | Degree of Influence (0 – 5) | Product of Weight and Influence
T1 | Distributed System | 2 | 2 | 4
T2 | Response Time/Performance Objectives | 1 | 3 | 3
T3 | End-User Efficiency | 1 | 2 | 2
T4 | Internal Processing Complexity | 1 | 3 | 3
T5 | Code Reusability | 1 | 2 | 2
T6 | Easy to Install | 0.5 | 0 | 0
T7 | Easy to Use | 0.5 | 2 | 1
T8 | Portability to Other Platforms | 2 | 0 | 0
T9 | System Maintenance | 1 | 2 | 2
T10 | Concurrent/Parallel Processing | 1 | 3 | 3
T11 | Security Features | 1 | 4 | 4
T12 | Access for Third Parties | 1 | 0 | 0
T13 | End User Training | 1 | 1 | 1
Technical Factor | - | - | - | 25

TECHNICAL COMPLEXITY FACTOR CALCULATION (TCF):
=0.6+0.01×TFactor
=0.85

ENVIRONMENTAL FACTORS:
Environment Factors | Weight | Degree of Influence (0 – 5) | Product of Weight and Influence
Familiar with Development Process | 1.5 | 3 | 4.5
Part Time Workers | -1 | 0 | 0
Analyst Capability | 0.5 | 0 | 0
Application Experience | 0.5 | 3 | 1.5
Object Oriented Experience | 1 | 2 | 2
Motivation | 1 | 4 | 4
Difficult Programming Language | -1 | 2 | -2
Stable Requirements | 2 | 3 | 6
Environmental Factor | - | - | 16

ENVIRONMENTAL FACTOR CALCULATION (EF):
=1.4+(-0.03×EFactor)
=0.92

USE CASE POINTS CALCULATION:
UCP=UUCW×TCF×EF
=146×0.85×0.92=114.172

EFFORT ESTIMATION - CONSTRUCTIVE COST MODEL (COCOMO)
Unable to apply COCOMO model at current stage for effort estimation. Accurate effort estimation will be calculated at the later stage of the design phase where Function Points estimation can be calculated.

RANGE OF EFFORT ESTIMATION
Duration:
15 × UCP to 30 × UCP
1713 <= Hours Required <= 3425

Duration per member:
286 <= Hours Required <= 571

Number of Days Required (3 Hours Daily):
95 <= Days Required <= 190

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`14/09/2023` - `16/09/2023`

</p>
</details>

**Comment by Cazyrah** [comment]
<details><summary>Work Done</summary>
<p>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/xackr/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/xackr/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/xackr/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">



</head>

<body lang=EN-SG style='tab-interval:36.0pt;word-wrap:break-word'>


<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>-UPDATE-<o:p></o:p></span></b></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>USE CASE
TRANSACTIONS COMPLEXITY:<o:p></o:p></span></b></p>



Use Case Complexity | Number of Transactions | Weight
-- | -- | --
Simple | <= 3 | 5
Average | 4 – 7 | 10
Complex | > 7 | 15

Use Case ID  | Number of Transactions | Use Case Complexity | Weight
-- | -- | -- | --
UC-1 | 2 | Simple | 5
UC-2 | 6 | Average | 10
UC-3 | 5 | Average | 10
UC-4 | 4 | Average | 10
UC-5 | 4 | Average | 10
UC-6 | 1 | Simple | 5
UC-7 | 3 | Simple | 5
UC-8 | 9 | Complex | 15
UC-9 | 7 | Average | 10
UC-10 | 3 | Simple | 5
UC-11 | 3 | Simple | 5
UC-12 | 3 | Simple | 5
UC-13 | 2 | Simple | 5
UC-14 | 5 | Average | 10
UC-15 | 5 | Average | 10
UC-16 | 5 | Average | 10
UC-17 | 2 | Simple | 5
UC-18 | 3 | Simple | 5
UC-19 | 2 | Simple | 5
UC-20 | 6 | Average | 10

<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>Unadjusted Transactions Weight of all Use Cases:<o:p></o:p></span></b></p>

Use Case Complexity | Weight | Number of Use Cases | Product of Weight and Number
-- | -- | -- | --
Simple | 5 | 10 | 50
Average | 10 | 9 | 90
Complex | 15 | 1 | 15
Unadjusted Transactions Weight |  |  | 155

<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>USE CASE ACTOR COMPLEXITY:<o:p></o:p></span></b></p>

Actor Complexity | Weight
-- | --
Simple | 1
Average | 2
Complex | 3

<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>Unadjusted Actors Weight of all Use Cases:<o:p></o:p></span></b></p>

Use Case ID  | Number of Actors | Actor Classification | Weight
-- | -- | -- | --
UC-1 | 1 | Complex | 3
UC-2 | 2 | Average, Complex | 2, 3
UC-3 | 2 | Average, Complex | 2, 3
UC-4 | 2 | Average, Complex | 2, 3
UC-5 | 1 | Simple | 1
UC-6 | 2 | Complex | 3
UC-7 | 2 | Complex | 3
UC-8 | 1 | Complex | 3
UC-9 | 1 | Complex | 3
UC-10 | 1 | Complex | 3
UC-11 | 1 | Complex | 3
UC-12 | 1 | Complex | 3
UC-13 | 1 | Complex | 3
UC-14 | 1 | Complex | 3
UC-15 | 2 | Complex | 3
UC-16 | 1 | Complex | 3
UC-17 | 1 | Complex | 3
UC-18 | 1 | Complex | 3
UC-19 | 1 | Complex | 3
UC-20 | 1 | Complex | 3

<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>Unadjusted Actors Weight of all Use Cases:<o:p></o:p></span></b></p>

Use Case Actor Complexity | Weight | Number of Actors | Product of Weight and Actors
-- | -- | -- | --
Simple | 1 | 1 | 1
Average | 2 | 1 | 2
Complex | 3 | 22 | 66
Unadjusted Actors Weight |  |  | 69

<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>TOTAL UNADJUSTED POINTS (UUCW):<o:p></o:p></span></b></p>

Unadjusted  Transactions  Weight+Unadjusted  Actors  Weight
= 155 + 69
= 224
<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>TECHNICAL COMPLEXITY FACTORS:<o:p></o:p></span></b></p>

Factor | Description | Weight | Degree of Influence (0 – 5) | Product of Weight and Influence
-- | -- | -- | -- | --
T1 | Distributed System | 2 | 2 | 4
T2 | Response Time/Performance Objectives | 1 | 3 | 3
T3 | End-User Efficiency | 1 | 2 | 2
T4 | Internal Processing Complexity | 1 | 3 | 3
T5 | Code Reusability | 1 | 2 | 2
T6 | Easy to Install | 0.5 | 0 | 0
T7 | Easy to Use | 0.5 | 2 | 1
T8 | Portability to Other Platforms | 2 | 0 | 0
T9 | System Maintenance | 1 | 2 | 2
T10 | Concurrent/Parallel Processing | 1 | 3 | 3
T11 | Security Features | 1 | 4 | 4
T12 | Access for Third Parties | 1 | 0 | 0
T13 | End User Training | 1 | 1 | 1
Technical Factor |  |  |  | 25

<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>TECHNICAL COMPLEXITY FACTOR CALCULATION (TCF):<o:p></o:p></span></b></p>

= 0.6 + 0.01 × TFactor
= 0.85
<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>ENVIRONMENTAL FACTORS:<o:p></o:p></span></b></p>

Environment Factors | Weight | Degree of Influence (0 – 5) | Product of Weight and Influence
-- | -- | -- | --
Familiar with Development Process | 1.5 | 3 | 4.5
Part Time Workers | -1 | 0 | 0
Analyst Capability | 0.5 | 0 | 0
Application Experience | 0.5 | 3 | 1.5
Object Oriented Experience | 1 | 2 | 2
Motivation | 1 | 4 | 4
Difficult Programming Language | -1 | 2 | -2
Stable Requirements | 2 | 3 | 6
Environmental Factor |  |  | 16

<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>ENVIRONMENTAL FACTOR CALCULATION (EF):<o:p></o:p></span></b></p>

= 1.4 + ( -0.03 × EFactor)
= 0.92
<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>USE CASE POINTS CALCULATION:<o:p></o:p></span></b></p>

UCP = UUCW × TCF × EF
= 224 × 0.85 × 0.92 = 175.168
<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>EFFORT ESTIMATION - CONSTRUCTIVE COST MODEL (COCOMO)<o:p></o:p></span></b></p>

Unable to apply COCOMO model at current stage for effort estimation. Accurate effort estimation will be calculated at the later stage of the design phase where Function Points estimation can be calculated.

<p class=MsoNormal><b><span style='font-size:25.0pt;line-height:107%;
font-family:"Cambria Math",serif;color:black;mso-themecolor:text1'>RANGE OF EFFORT ESTIMATION<o:p></o:p></span></b></p>

Duration:
15 × UCP to 30 × UCP
2628 <= Hours Required <= 5255

Duration per member:
438 <= Hours Required <= 876

Number of Days Required:
146 <= Days Required (3 Hours Daily) <= 292    to    63 <= Days Required (7 Hours Daily) <= 125


</body>

</html>

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`18/09/2023` - `21/09/2023`

</p>
</details>
