### ISSUE TITLE
[1.1.2] Interview Script

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#8]
<details><summary>Task Title ID</summary>
<p>
#8
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Details</summary>
<p>

`Do a preparation for the client meeting by creating a script for the meeting.`

</p>
</details> 
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Goals</summary>
<p>

`Interview Script is prepared and ready for the meeting.`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Success - Completion Details:</summary>
<p>

`Interview Script that is able to suffice the 15 min meeting period.`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`2 days`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`03/09/2023` - `04/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [x] Zac

- [ ] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Task Status</summary>
<p>

`Complete`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`Low priority`

</p>
</details>

**Comment by Cazyrah** [comment]
<details><summary>Work Done</summary>
<p>

Good morning Mr Chee. Thank you for taking the time to meet with us today. My name is Den, and I’ll be leading the team that will be working on your project. With me today is Zachary, Hakim, Malcolm, Brendan, and Rudhi, who will be playing a crucial role in this project. The objective of today’s meeting is to understand more about the company to meet your needs and expectations. 

Let us begin with the first question:
What are the constraints and challenges from your previous methods on workload management that you would like to address with this app?

Next, we will proceed to questions on requirements: 
i) Does the website have to be mobile friendly, or are you strictly using it on a computer?
ii) How do you want it visualized on the landing page? (By staff, by date/time/calendar, by workload)? What kind of information to show along with workload? (Staff name, type, timing)? How to visualize workload for each staff type? (Driver, technician)
iii) Can this be edited later on? How are jobs allocated? By hours? Per location?
iv) What is the relevant information? What kind of staff? (Driver, tech) How easy? What makes allocating a job easier? Is staff availability and job allocation on the same page?
v) Will staff be able to see the availability of other staff? Should they be able to see? If so, can the driver see tech availability? How many days before the actual day can staff edit? (e.g. cannot edit 3 days prior)
vi) Will staff be able to see if others prefer a job? Should they be able to see?
vii) Upon rejection, will the manager be informed about it?How many days before the actual day can staff reject? Can staff reject the week itself?
viii) Is this on the same web page?

Finally, we have some domain related questions:
i) Can you elaborate on how staff can indicate their job preference for the week?
ii) Can you elaborate on how end-users will be able to request aircon services through the app? Will there be specific details they need to provide, and how will these requests be presented to the manager?
iii) It is mentioned that employees must inform their availability by Wednesday for the upcoming week's planning. How will the system handle late submissions or changes in availability after the deadline?
iv) For IT administrators overseeing user management, could you provide more details on what tasks they would handle? Will they also have visibility into workload data?
v) Is there a limit to the number of MCs and offs?
vi) Are there any backup plans for unforeseen circumstances such as last minute unavailability and vehicle breakdown?
vii) How do you want each staff member to be identified during login?
viii) How long does van servicing take?
ix) Is each driver assigned to only a particular van?
x) For staff that have over 40 hours of jobs allocated, will they still be available for job allocation or should they be flagged out by the system?
xi) Will the website be intranet or internet?
xii) Should there be a single shared admin (manager) account with the same login credentials for all managers, or would you prefer to have unique login accounts for each individual manager?

That concludes all our questions we have for today. We would like to thank you, Mr. Chee, for your time and valuable insights.
</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Start Date - End Date</summary>
<p>

`03/09/2023` - `04/09/2023`

</p>
</details>
